### ISSUE TITLE
A way to make the addon start logging when nvda starts

### ISSUE THREAD

**Issue by VIPPotato** [opensourcesys/speechLogger#9]
So, I have a small PC I use as a server, and I gave remote access to a few trusted people. Just in case, I would appreciate an option to make speech logging start right after nvda starts up with out a need to press any key combo. This will be usefull for example after windows finishes updating and restarts itself. I'm talking about local speech logging. It would also be cool that each time nvda is restarted a new file with the date and time is being made. That would make browsing through logs easier.

**Comment by XLTechie** [comment]
@VIPPotato I agree. Will do that ASAP.

As to your second point, that is already on the to-do list. See 
https://github.com/opensourcesys/speechLogger/issues/4

**Comment by XLTechie** [comment]
@VIPPotato I have implemented an initial version of what you requested.
You can try it out by downloading the [23.3.002 dev version](https://github.com/opensourcesys/speechLogger/releases/download/v23.3.002-dev/speechLogger-23.3.002.nvda-addon) from the Add-on Store, or by directly downloading it [here](https://github.com/opensourcesys/speechLogger/releases/download/v23.3.002-dev/speechLogger-23.3.002.nvda-addon).
To enable the feature, go to NVDA menu > Preferences > Settings > Speech Logger category. Then Shift+tab or tab to the last combo box: "Begin logging at startup", and set the option to "Always". Then press enter, and don't forget to save your settings if necessary.

This feature is not documented yet, and I want to do a few unrelated things before a production release with this feature, but you can try it now if you like.
